dist: xenial   # required for Python >= 3.7

env:
  global:
  - TESS=4.0.0

services:
  - xvfb

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - wget https://github.com/tesseract-ocr/tesseract/archive/$TESS.tar.gz
  - tar xvf $TESS.tar.gz
  - mv tesseract-$TESS tesseract
  - export TESSERACT_INSTALL=$HOME/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - export LIBLEPT_HEADERSDIR="$TESSERACT_INSTALL/include"
  - export LDFLAGS="-L$TESSERACT_INSTALL/lib"
  - export CFLAGS="-I$TESSERACT_INSTALL/include"

script:
  - nose2 -v