dist: xenial   # required for Python >= 3.7

services:
  - xvfb

addons:
  apt:
    update: true
    packages:
      - tesseract-ocr

language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - nose2 -v